---
- name: Configure all nodes
  become: True
  hosts: all
  roles:
    - pkg
    - common

- name: Configure Control Plane
  become: True
  hosts: master
  roles:
    - init

- name: Configure worker nodes
  become: True
  hosts: nodes
  roles:
    - join

- name: Configure Dashboard UI
  become: False
  hosts: master
  roles:
    - dashboard
